# Copyright 2024 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: lineage-filter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: mysql
        image: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: db_root_password
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
            subPath: "mysql"
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS pathwarden;
    USE pathwarden;
    CREATE TABLE traces (
      trace VARCHAR(255) NOT NULL,
      PRIMARY KEY (trace)
    );
    CREATE TABLE labels (
      label VARCHAR(255) NOT NULL,
      PRIMARY KEY (label)
    );
    CREATE TABLE services (
      service VARCHAR(255) NOT NULL,
      is_db BOOL NOT NULL DEFAULT 0,
      PRIMARY KEY (service)
    );
    CREATE TABLE traces_labels (
      trace VARCHAR(255) NOT NULL,
      label VARCHAR(255) NOT NULL,
      FOREIGN KEY (trace) REFERENCES traces(trace),
      FOREIGN KEY (label) REFERENCES labels(label),
      PRIMARY KEY (trace, label)
    );
    CREATE TABLE services_labels (
      service VARCHAR(255) NOT NULL,
      label VARCHAR(255) NOT NULL,
      FOREIGN KEY (service) REFERENCES services(service),
      FOREIGN KEY (label) REFERENCES labels(label),
      PRIMARY KEY (service, label)
    );
    CREATE TABLE parent_child_labels (
      CHECK (parent <> child),
      id INT NOT NULL AUTO_INCREMENT,
      parent VARCHAR(255) NOT NULL,
      child VARCHAR(255) NOT NULL,
      request_labels VARCHAR(1023) NOT NULL,
      response_labels VARCHAR(1023),
      policy_violation VARCHAR(1023),
      FOREIGN KEY (parent) REFERENCES services(service),
      FOREIGN KEY (child) REFERENCES services(service),
      PRIMARY KEY (id, parent, child)
    );
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    app: db
  type: LoadBalancer